name: BP_SlideVideoSync
channels:
  - conda-forge
dependencies:
  - cairo
  - ffmpeg
  - matplotlib
  - numpy
  - pdf2image
  - pillow
  - pip
  - poppler
  - pypdf
  - pytest
  - python
  - scikit-learn
  - pyinstaller
  - pip:
      - opencv-contrib-python
      - opencv-python
      - pyside6
      - shapely
